FROM ant
MAINTAINER Ivan Ermilov <ivan.s.ermilov@gmail.com>

RUN apt-get update \
    && apt-get install -y gcc \
    && apt-get install -y g++ \
    && apt-get install -y libkrb5-dev \
    && apt-get install -y libmysqlclient-dev \
    && apt-get install -y libssl-dev \
    && apt-get install -y libsasl2-dev \
    && apt-get install -y libsasl2-modules-gssapi-mit \
    && apt-get install -y libsqlite3-dev \
    && apt-get install -y libtidy-0.99-0 \
    && apt-get install -y libxml2-dev \
    && apt-get install -y libxslt-dev \
    && apt-get install -y make \
    && apt-get install -y maven \
    && apt-get install -y libldap2-dev \
    && apt-get install -y python-dev \
    && apt-get install -y python-setuptools \
    && apt-get install -y libgmp3-dev \
